import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <Link href="/">
              <span>Home</span>
            </Link>{" "}
            <Link href="/about">
              <span>About</span>
            </Link>{" "}
            <Link href="/posts">
              <span>Posts</span>
            </Link>
          </nav>
        </header>
        <br />
        {children}
        <br />
        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
